spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./adminExhangeDb
    username: ""
    password: ""

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 7070

exchange:
  service-endpoint: http://localhost:7070/exchange


logging:
  level:
    com.github.dockerjava: WARN